development:
  adapter: mysql2
  encoding: utf8
  database: service_watcher-dev
  pool: 5
  username: service_watcher
  password: PRN45AzP87VcN2an
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: service_watcher-test
  pool: 5
  username: service_watcher
  password: PRN45AzP87VcN2an
  socket: /var/run/mysqld/mysqld.sock
